print "--c  cylon mode"
print "--g  charging mode"
print "--l  loading mode"
print "--k  Knight Rider mode"
print "--w  warning mode"
print "--a  alert mode"
print "--d  Demo mode"
print "--help  shows this message"
